# import Comment from 'iname.gql'

type Symbol implements IName {
    baseId:String!
    quoteId:String!
    symbolId:String!
    open:Float!
    close:Float!
    low:Float!
    high:Float!
    change_from_open:Float!
    change_to_high:Float!
    timeframe:Int!
    position:Int!
    position_good_spread:Int
    spread_percentage:Float!
}

type Subscription{
    signalLoaded:[Symbol!]!
}